# Generated by Django 5.1.6 on 2025-05-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TeamApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="image",
            field=models.ImageField(upload_to="imaginijucatori"),
        ),
    ]
